#  _____     ___ ____ 
#   ____|   |    ____|      PS2 Open Source Project
#  |     ___|   |____       
#  
#--------------------------------------------------------------------------
#
#    Copyright (C) 2008 - Neme & jimmikaelkael (www.psx-scene.com) 
#
#    This program is free software; you can redistribute it and/or modify
#    it under the terms of the Free McBoot License.
#    
#	 This program and any related documentation is provided "as is"
#	 WITHOUT ANY WARRANTIES, either express or implied, including, but not
# 	 limited to, implied warranties of fitness for a particular purpose. The
# 	 entire risk arising out of use or performance of the software remains
# 	 with you.
#    In no event shall the author be liable for any damages whatsoever
# 	 (including, without limitation, damages to your hardware or equipment,
# 	 environmental damage, loss of health, or any kind of pecuniary loss)
# 	 arising out of the use of or inability to use this software or
# 	 documentation, even if the author has been advised of the possibility
# 	 of such damages.
#
#    You should have received a copy of the Free McBoot License along with
#    this program; if not, please report at psx-scene :
#    http://psx-scene.com/forums/freevast/
#
#--------------------------------------------------------------------------     
#
# MakeFile
#
# ------------------------------------------------------------------------

EE_ELF = maploader-11184.elf
EE_BIN = maploader-11184.bin
EE_OBJS = main.o rpc.o deadlocked.o 

SBV_SRC = sbv/src

EE_OBJS += usbhdfsd.o usbserv.o

EE_LIBS := -lkernel -lpatches
EE_INCS := -I$(PS2DEV)/gsKit/include -I$(PS2SDK)/ports/include -Isbv/include -Isbv/src

# DL APPID is 11184
EE_DEFS = -DAPPID=11184

include $(PWD)/Makefile.rules

usbhdfsd.s:
	bin2s irx/usbhdfsd/usbhdfsd.irx usbhdfsd.s usb_mass_irx
			
usbserv.s:
	$(MAKE) -C irx/usbserv
	bin2s irx/usbserv/usbserv.irx usbserv.s usbserv_irx

include $(PWD)/Makefile.pref
include $(PWD)/Makefile.eeglobal
